name: "CI (integracao Continua): First Action"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print a string
        run: echo Hello, world!